language: node_js
node_js:
  - "10.16.2"
before_script:
  - npm install -g @vue/cli
script: 
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${github_token}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: "/dist"
  on:
    branch: master